= Uploading the policy to Exchange

Custom policies need to be published to Exchange so users can obtain and apply them to APIs. API Manager lists custom policies published as assets of the Organization.

Anypoint Exchange provides a Maven facade that enables Maven clients to publish and consume assets using Maven and publish custom policies to Exchange.

You must have a unique artifact name and organization ID to publish your asset.

When creating the custom policy project using the archetype, necessary plugins for uploading are already defined.

Only, configuring the correct credentials is left to do. Update the settings.xml file in your Maven .m2 directory with your Exchange credentials.

*Example settings.xml file*

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
       <id>Repository</id>
       <username>myusername</username>
       <password>mypassword</password>
     </server>
  </servers>
</settings>
----

After that, run `mvn deploy` to publish the policy to Exchange.

The custom policy is now available for you to apply to APIs that belong to the specified organization.

== See Also
**** link:/api-manager/v/2.x/custom-policy-packaging-policy[Packaging a Custom Policy]
**** link:/api-manager/v/2.x/custom-policy-uploading-to-exchange[Uploading to Exchange]
**** link:/api-manager/v/2.x/custom-policy-4-reference[Reviewing Custom Policy General Reference]
