= Upgrade to Anypoint Platform Private Cloud, Version 2.0

This topic provides information about upgrading Anypoint Platform Private Cloud Edition to the most recent version. This version supports the following migration paths:

[%header%autowidth.spread]
|===
| Base Version | Intermediate Versions | Target Version | Comments
| 1.7.x | N/A | 2.0 | Direct upgrade is supported
| 1.6.x | 1.7.1 | 2.0 | Must upgrade to version 1.7.1
| 1.5.x | 1.6.1, 1.7.1 | 2.0 | Must upgrade to 1.6.1, then 1.7.1 before upgrading to 2.0.
|===

See link:/anypoint-private-cloud/v/1.6/upgrade[About Migrating Anypoint Platform Private Cloud Edition] for information on upgrading to version 1.6.1. See link:/anypoint-private-cloud/v/1.7/upgrade[About Migrating Anypoint Platform Private Cloud Edition] for information on upgrading to version 1.7.1.

[WARNING]
During the migration process, there will be some downtime as each node is updated. 


== Prerequisites

Before migrating, ensure that you have performed and met the following prerequisites:

* Perform a backup of your system as described in link:backup-and-disaster-recovery[About Backup and Recovery]. If you are upgrading from an older version that requires multiple intermediate upgrades you must backup each intermediate version before proceding to the next.

* Anypoint Private Cloud, version 2.0 requires that you have an NFS server installed and configured. Ensure that this is installed before beginning the upgrade. See link:/anypoint-private-cloud/v/2.0/prereq-network[Private Cloud Edition Network Requirements]

* Ensure that your environment meets all of the system and network requirements described in link:/anypoint-private-cloud/v/2.0/prereq-workflow[Workflow: Install and Verify Prerequisites for Physical Servers]

* Enable TCP ports `53`, `3011`, `3012` intra-node to allow communication with the database cluster.

* Ensure you have permission to run the `sudo` command on the node where you launch the migration tool.

* Ensure the `kubectl` command is available in the node where you are performing the migration. To verify that `kubectl` is installed, run the following:
+
----
$ sudo gravity enter
$ kubectl
----

== Procedure

. Obtain a link to the installer from your customer success representative.

. Use `ssh` to login to the master node of your cluster.
+
In a 3-node environment, all nodes are master nodes. To find the master nodes in a 6-node environment, run the following command:
+
----
kubectl get node --show-labels | grep gravitational.io/k8s-role=master
----
+
By performing these procedures from the master node, the upgrade scripts are able to update the entire platform.

. Uncompress the application archive.
+
----
tar -xvf anypoint-1.2.0-installer.tar.gz
----

. Navigate to the `anypoint-2.0` directory, then run the upload script.
+
----
cd anypoint-2.0
sudo ./upgrade
----
+
This command updates the platform to the current version and restarts each pod in the cluster.
+
----
$ sudo ./upgrade
-> initializing upload
-> uploading update package
importing anypoint:2.0
synchronizing anypoint:2.0 with Docker registry at 172.31.0.26:5000
synchronizing anypoint:2.0 with Docker registry at 172.31.0.45:5000
synchronizing anypoint:2.0o with Docker registry at 172.31.0.5:5000
anypoint:2.0 has been uploaded
updating anypoint from 1.7.1 to 2.0
update operation (bae00abf-98a7-4ca9-b0d2-06f3bfea3024) has been started
the cluster is updating in background
----
+
Depending on your network configuration, this command may take a while to complete. Wait until the command finishes before proceeding to the next step.

. Verify that the migration was successful by performing one of the following:
+
* Run the following command from the node where you performed the upgrade:
+
----
$ sudo gravity enter
$ kubectl get pods
----
+
* Login to the Ops Center at the following URL:
+
----
https://{platform-host}:9500
----

. Configure Anypoint Private Cloud to use your NFS server.
+
After upgrading Anypoing Private Cloud, you configure it to use the required NFS server.
+
.. From Anypoint Platform, select *Access Management*.
.. Click *NFS Settings*.
.. Enter the domain name of your NFS server.
.. Enter the path to your NFS server.
.. Click *Test NFS Server*.
.. Click *Save*.



