= About Dynamic Ports
:version-info: 2.0 and later
:keywords: mule, esb, tests, qa, quality assurance, verify, functional testing, unit testing, stress testing, assert

The Assert Equals Event Processor allows you to run assertions in order to validate the state of a Mule Event's content. +
This Event Processor can be used to validate the Mule Event after the production code runs.

For example, to assert that a payload is equal to a certain value, you can configure the Assert-Equals processor the following way:

[source,xml,linenums]
----
<munit-tools:assert-equals
  actual="#[payload]"
  expected="#['example']"
  message="The payload should be ‘example’"/>
----

If this assertion fails, the processor throws a `java.lang.AssertionError`.

== See Also

* link:/munit/v/2.2/munit-matchers[About MUnit Matchers]
* link:/munit/v/2.2/fail-event-processor[About Fail Event Processor]
* link:/munit/v/2.2/set-event-processor[About Set Event Processor]
* link:/munit/v/2.2/mock-message-processor[About Mock When Event Processor]
* link:/munit/v/2.2/verify-message-processor[About Verify Event Processor]
