= Anypoint Platform Private Cloud Edition 2.0.0 Release Notes

*August 24, 2017*

== New Features and Enhancements

This version of Anypoint Platform Private Cloud Edition contains the following features and enhancements:

[%header,cols="2*a"]
|===
| Feature | Description
|===

== Installing

See link:/anypoint-private-cloud/v/1.7/install-workflow[Workflow: Install Anypoint Private Cloud] for information on how to install Anypoint Platform Private Cloud Edition.

== Upgrading to 2.0.0

See link:/anypoint-private-cloud/v/2.0/upgrade[To Migrate to Anypoint Platform Private Cloud, Version 1.7.0] for information on how to upgrade to the current version.

Before upgrading, you must backup your system as described in link:/anypoint-private-cloud/v/2.0/backup-and-disaster-recovery[To Backup and Restore Your System].

== Software Compatibility

[%header,cols="2*a"]
|===
| Compatible with |Version
| Mule runtime | 3.7.x - 3.9.0
| API Gateway Runtime | 2.1.x - 2.2.x
| Runtime Manager Agent | 1.5.3 - 1.9.0
| Infrastructure providers |
* VMWare
* Bare Metal
| Compatible browsers when running the installer |
* Firefox (latest version)
* Chrome (latest version)
* Safari (latest version)
|===

== Fixed Issues

[%header%autowidth.spread]
|===
| Issue | Description
|===

== Known Issues

[%header%autowidth.spread]
|===
| Description | Workaround
|===


== Anypoint Platform Features

The following sections outline the Anypoint Platform features and bug fixes added to this version of Anypoint Platform Private Cloud Edition. This information is compiled from the release notes of each platform component.

=== Anypoint Runtime Manager

[%header,cols="2*a"]
|===
| Release | Features and Issue Fixes
|===

=== Access Management

[%header,cols="2*a"]
|===
| Release | Features and Issue Fixes
|===

=== Exchange

[%header,cols="2*a"]
|===
| Release | Features and Issue Fixes
|===


=== Design Center

[%header,cols="2*a"]
|===
| Release | Features and Issue Fixes
|===

=== API Designer

[%header,cols="2*a"]
|===
| Release | Features and Issue Fixes
|===
